apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mpod
  name: mpod
spec:
  serviceName: mpod
  replicas: 1
  selector:
    matchLabels:
      app: mpod
  template:
    metadata:
      labels:
        app: mpod
    spec:
      containers:
      - image: docker.io/library/mpod
        name: mpod
        imagePullPolicy: Never
        command: ["service", "ssh", "start", "-D"]
