apiVersion: v1
kind: Service
metadata:
  labels:
    app: mpod
  name: mpod
spec:
  clusterIP: None
  ports:
  - name: ssh
    port: 80
    protocol: TCP
    targetPort: 22
  selector:
    app: mpod
  type: ClusterIP
